"""Machine-readable CLI exit codes."""

SUCCESS = 0
VALIDATION_FAILED = 10
FETCH_FAILED = 20
RENDER_FAILED = 21
HEALING_FAILED = 30
LLM_UNAVAILABLE = 31
CONFIG_ERROR = 40
NOT_FOUND = 44
INTERNAL_ERROR = 99
