"""Interactive `scrape setup` — first-run configuration."""

from __future__ import annotations

import os
import sys
from pathlib import Path

import typer
from rich.console import Console
from rich.panel import Panel

from healscrape import __version__
from healscrape.cli.starters import STARTER_PROFILE, STARTER_SCHEMA

console = Console(stderr=True)


def _default_env_lines(data_dir: str, gemini_key: str, model: str) -> list[str]:
    lines = [
        "# Generated by: scrape setup",
        f"HEALSCRAPE_DATA_DIR={data_dir}",
        "",
    ]
    if gemini_key:
        lines.append(f"GEMINI_API_KEY={gemini_key}")
    else:
        lines.append("# GEMINI_API_KEY=")
    lines.append(f"HEALSCRAPE_GEMINI_MODEL={model}")
    lines.append("")
    return lines


def run_setup(
    *,
    env_file: Path,
    non_interactive: bool,
    with_starters: bool,
    starters_dir: Path,
    force_starters: bool,
) -> int:
    if non_interactive:
        console.print(
            Panel.fit(
                "[bold]Non-interactive[/bold]\n"
                "1. Copy [cyan].env.example[/cyan] → [cyan].env[/cyan]\n"
                "2. Set [bold]GEMINI_API_KEY[/bold] for healing\n"
                "3. Optional: [bold]HEALSCRAPE_DATA_DIR[/bold] (default [dim]~/.healscrape[/dim])\n"
                f"4. Run [cyan]scrape doctor[/cyan]  ·  healscrape {__version__}",
                title="healscrape setup",
            )
        )
        return 0

    if not sys.stdin.isatty():
        console.print(
            "[red]No TTY on stdin.[/red] Use [cyan]scrape setup --non-interactive[/cyan] "
            "or run this command in a normal terminal."
        )
        return 40

    console.print(Panel.fit(f"[bold]healscrape[/bold] {__version__}\nInteractive setup", title="Welcome"))

    default_data = str(Path.home() / ".healscrape")
    data_dir = typer.prompt("Data directory (DB, snapshots, traces)", default=default_data).strip()
    if not data_dir:
        data_dir = default_data

    if typer.confirm("Configure Gemini for healing?", default=True):
        key = typer.prompt("GEMINI_API_KEY", hide_input=True, default="").strip()
        model = typer.prompt("Model id", default="gemini-2.0-flash").strip() or "gemini-2.0-flash"
    else:
        key = ""
        model = "gemini-2.0-flash"

    env_path = env_file.expanduser().resolve()
    if env_path.exists():
        if not typer.confirm(f"{env_path} already exists. Overwrite?", default=False):
            console.print("[yellow]Aborted[/yellow] (no file written).")
            return 1

    env_path.parent.mkdir(parents=True, exist_ok=True)
    content = "\n".join(_default_env_lines(data_dir, key, model))
    env_path.write_text(content, encoding="utf-8")
    console.print(f"[green]Wrote[/green] {env_path}")

    os.environ["HEALSCRAPE_DATA_DIR"] = data_dir
    if key:
        os.environ["GEMINI_API_KEY"] = key

    if with_starters and typer.confirm("Create starter page.schema.json + site.yaml here?", default=True):
        starters_dir = starters_dir.expanduser().resolve()
        starters_dir.mkdir(parents=True, exist_ok=True)
        for name, body in (("page.schema.json", STARTER_SCHEMA), ("site.yaml", STARTER_PROFILE)):
            p = starters_dir / name
            if p.exists() and not force_starters:
                console.print(f"[yellow]Skip[/yellow] (exists): {p}")
                continue
            p.write_text(body.strip() + "\n", encoding="utf-8")
            console.print(f"[green]Wrote[/green] {p}")

    console.print(
        Panel.fit(
            "[bold]Try[/bold]\n"
            "  [cyan]scrape doctor[/cyan]\n"
            "  [cyan]scrape quick https://example.com[/cyan]\n"
            "  [cyan]scrape extract[/cyan] URL [cyan]page.schema.json[/cyan]",
            title="Next",
        )
    )
    return 0
